[package]
name = "sub1_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base_lib = { path = "../base_lib/" }
pyo3 = { version = "0.17", features = ["extension-module"] }
